# Operations
#

################### USER QUERIES ###################

query getUsers {
  users {
    id
    email
    name
    shareBooks
    shareMovies
  }
}

query getUser($userId: ID!) {
  user(id: $userId) {
    id
    email
    name
    shareBooks
    shareMovies
  }
}

################### BOOK QUERIES ###################

query getBooks($userId: ID!) {
  books(userId: $userId) {
    id
    author
    title
    mode
    completed
  }
}

query getBook($bookId: ID!) {
  book(id: $bookId) {
    id
    author
    title
    mode
    completed
  }
}

query getBooksNextPage($userId: ID!) {
  booksNextPage(userId: $userId, first: 10, after: "57b76ded8ae9630300be6d5c") {
    books {
      id
      author
      title
      completed
    }
    cursor
  }
}

query getBooksPreviousPage($userId: ID!) {
  booksPreviousPage(userId: $userId, last: 10, before: "57b76ded8ae9630300be6d51") {
    books {
      id
      author
      title
      completed
    }
    cursor
  }
}

################### MOVIE QUERIES ###################

query getMovies($userId: ID!) {
  movies(userId: $userId) {
    title
    year
    notes
    completed
    imdbId
  }
}

query getMovie($movieId: ID!) {
  movie(id: $movieId) {
    id
    title
    year
    notes
    imdbId
    completed
  }
}

################### BOOK MUTATIONS ###################

mutation CreateBook($bookContent: CreateBookContent!) {
  createBook(bookContent: $bookContent) {
    id
    userId
    author
    title
    mode
    completed
  }
}

mutation UpdateBook($bookId: ID!, $bookContent: UpdateBookContent!) {
  updateBook(id: $bookId, bookContent: $bookContent) {
    id
    author
    title
    mode
    completed
  }
}

mutation DeleteBook($bookId: ID!) {
  deleteBook(id: $bookId) {
    id
    userId
    author
    title
  }
}

################### MOVIE MUTATIONS ###################

mutation CreateMovie($movieContent: CreateMovieContent!) {
  createMovie(movieContent: $movieContent) {
    id
    title
    year
    notes
    imdbId
    completed
  }
}

mutation UpdateMovie($movieId: ID!, $movieContent: UpdateMovieContent!) {
  updateMovie(id: $movieId, movieContent: $movieContent) {
    id
    title
    year
    notes
    imdbId
    completed
  }
}

mutation DeleteMovie($movieId: ID!) {
  deleteMovie(id: $movieId) {
    id
    userId
    title
    year
  }
}

# Variables
#

{
  "userId": "57a8ba0bd901937c0275bce5",

  "bookId": "660b0ac895626cd739f45a0e",

  "movieId": "660a99c750258cd8f67f87d6",

  "bookContent": {
    "userId": "57a8ba0bd901937c0275bce5",
    "author": "Author-42",
    "title": "Title-42",
    "mode": "MIXED",
    "completed": "2024-04-01",
  },

 "movieContent": {
    "userId": "57a8ba0bd901937c0275bce5",
    "title": "Title-42",
    "year": "2024",
    "notes": "answer: 42",
    "imdbId": "tt424242",
    "completed": "2024-04-01",
  },
}

# Headers
#

Authorization Bearer ...
