# Operation
#
query getUsers {
  users {
    id
    email
    name
    shareBooks
    shareMovies
  }
}

query getUser($userId: ID!) {
  user(id: $userId) {
    id
    email
    name
    shareBooks
    shareMovies
  }
}

query getBooks($userId: ID!) {
  books(userId: $userId) {
    author
    title
    mode
    completed
  }
}

query getBook($bookId: ID!) {
  book(id: $bookId) {
    id
    author
    title
    mode
    completed
  }
}

query getMovies($userId: ID!) {
  movies(userId: $userId) {
    title
    year
    notes
    completed
    imdbId
  }
}

mutation CreateBook($bookContent: CreateBookContent!) {
  createBook(bookContent: $bookContent) {
    id
    author
    title
    mode
    completed
  }
}

mutation UpdateBook($bookId: ID!, $bookContent: UpdateBookContent!) {
  updateBook(id: $bookId, bookContent: $bookContent) {
    id
    author
    title
    mode
    completed
  }
}

mutation DeleteBook($bookId: ID!) {
  deleteBook(id: $bookId) {
    id
    userId
    author
    title
  }
}

# Variables
#
{
  "userId": "57a8ba0bd901937c0275bce5",

  "bookId": "6608531b81bdbf80bfecbd7b",

  "bookContent": {
    "userId": "57a8ba0bd901937c0275bce5",
    "author": "Author-42",
    "title": "Title-42",
    "mode": "MIXED",
    "completed": "2024-04-01",
  },
}
